export const REQUEST_ADD_ITEM = 'REQUEST_ADD_ITEM';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAILURE = 'ADD_ITEM_FAILURE';

export const REQUEST_UPDATE_ITEM = 'REQUEST_UPDATE_ITEM';
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
export const UPDATE_ITEM_FAILURE = 'UPDATE_ITEM_FAILURE';

export const REQUEST_ADD_CHECKLIST = 'REQUEST_ADD_CHECKLIST';
export const ADD_CHECKLIST_SUCCESS = 'ADD_CHECKLIST_SUCCESS';
export const ADD_CHECKLIST_FAILURE = 'ADD_CHECKLIST_FAILURE';

export const REQUEST_UPDATE_CHECKLIST = 'REQUEST_UPDATE_CHECKLIST';
export const UPDATE_CHECKLIST_SUCCESS = 'UPDATE_CHECKLIST_SUCCESS';
export const UPDATE_CHECKLIST_FAILURE = 'UPDATE_CHECKLIST_FAILURE';

export const REQUEST_LOAD_CHECKLISTS = 'REQUEST_LOAD_CHECKLISTS';
export const LOAD_CHECKLISTS_SUCCESS = 'LOAD_CHECKLISTS_SUCCESS';
export const LOAD_CHECKLISTS_FAILURE = 'LOAD_CHECKLISTS_FAILURE';

export const REQUEST_DELETE_CHECKLIST = 'REQUEST_DELETE_CHECKLIST';
export const DELETE_CHECKLIST_SUCCESS = 'DELETE_CHECKLIST_SUCCESS';
export const DELETE_CHECKLIST_FAILURE = 'DELETE_CHECKLIST_FAILURE';

export const REQUEST_DELETE_ITEM = 'REQUEST_DELETE_ITEM';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_FAILURE = 'DELETE_ITEM_FAILURE';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REQUEST_REGISTRATION = 'REQUEST_REGISTRATION';
export const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE';

export const CHECK_AUTH = 'CHECK_AUTH';
export const SET_AUTH_TO_FALSE = 'SET_AUTH_TO_FALSE';
