export class SupportedLanguages {
    // list of supported language is taken from https://tech.yandex.com/translate/doc/dg/concepts/api-overview-docpage/
    languages = [
        { name: 'Azerbaijan', code: 'az' },
        { name: 'Malayalam', code: 'ml' },
        { name: 'Albanian', code: 'sq' },
        { name: 'Maltese', code: 'mt' },
        { name: 'Amharic', code: 'am' },
        { name: 'Macedonian', code: 'mk' },
        { name: 'English', code: 'en' },
        { name: 'Maori', code: 'mi' },
        { name: 'Arabic', code: 'ar' },
        { name: 'Marathi', code: 'mr' },
        { name: 'Armenian', code: 'hy' },
        { name: 'Mari', code: 'mhr' },
        { name: 'Afrikaans', code: 'af' },
        { name: 'Mongolian', code: 'mn' },
        { name: 'Basque', code: 'eu' },
        { name: 'German', code: 'de' },
        { name: 'Bashkir', code: 'ba' },
        { name: 'Nepali', code: 'ne' },
        { name: 'Belarusian', code: 'be' },
        { name: 'Norwegian', code: 'no' },
        { name: 'Bengali', code: 'bn' },
        { name: 'Punjabi', code: 'pa' },
        { name: 'Burmese', code: 'my' },
        { name: 'Papiamento', code: 'pap' },
        { name: 'Bulgarian', code: 'bg' },
        { name: 'Persian', code: 'fa' },
        { name: 'Bosnian', code: 'bs' },
        { name: 'Polish', code: 'pl' },
        { name: 'Welsh', code: 'cy' },
        { name: 'Portuguese', code: 'pt' },
        { name: 'Hungarian', code: 'hu' },
        { name: 'Romanian', code: 'ro' },
        { name: 'Vietnamese', code: 'vi' },
        { name: 'Russian', code: 'ru' },
        { name: 'Haitian (Creole)', code: 'ht' },
        { name: 'Cebuano', code: 'ceb' },
        { name: 'Galician', code: 'gl' },
        { name: 'Serbian', code: 'sr' },
        { name: 'Dutch', code: 'nl' },
        { name: 'Sinhala', code: 'si' },
        { name: 'Hill Mari', code: 'mrj' },
        { name: 'Slovakian', code: 'sk' },
        { name: 'Greek', code: 'el' },
        { name: 'Slovenian', code: 'sl' },
        { name: 'Georgian', code: 'ka' },
        { name: 'Swahili', code: 'sw' },
        { name: 'Gujarati', code: 'gu' },
        { name: 'Sundanese', code: 'su' },
        { name: 'Danish', code: 'da' },
        { name: 'Tajik', code: 'tg' },
        { name: 'Hebrew', code: 'he' },
        { name: 'Thai', code: 'th' },
        { name: 'Yiddish', code: 'yi' },
        { name: 'Tagalog', code: 'tl' },
        { name: 'Indonesian', code: 'id' },
        { name: 'Tamil', code: 'ta' },
        { name: 'Irish', code: 'ga' },
        { name: 'Tatar', code: 'tt' },
        { name: 'Italian', code: 'it' },
        { name: 'Telugu', code: 'te' },
        { name: 'Icelandic', code: 'is' },
        { name: 'Turkish', code: 'tr' },
        { name: 'Spanish', code: 'es' },
        { name: 'Udmurt', code: 'udm' },
        { name: 'Kazakh', code: 'kk' },
        { name: 'Uzbek', code: 'uz' },
        { name: 'Kannada', code: 'kn' },
        { name: 'Ukrainian', code: 'uk' },
        { name: 'Catalan', code: 'ca' },
        { name: 'Urdu', code: 'ur' },
        { name: 'Kyrgyz', code: 'ky' },
        { name: 'Finnish', code: 'fi' },
        { name: 'Chinese', code: 'zh' },
        { name: 'French', code: 'fr' },
        { name: 'Korean', code: 'ko' },
        { name: 'Hindi', code: 'hi' },
        { name: 'Xhosa', code: 'xh' },
        { name: 'Croatian', code: 'hr' },
        { name: 'Khmer', code: 'km' },
        { name: 'Czech', code: 'cs' },
        { name: 'Laotian', code: 'lo' },
        { name: 'Swedish', code: 'sv' },
        { name: 'Latin', code: 'la' },
        { name: 'Scottish', code: 'gd' },
        { name: 'Latvian', code: 'lv' },
        { name: 'Estonian', code: 'et' },
        { name: 'Lithuanian', code: 'lt' },
        { name: 'Esperanto', code: 'eo' },
        { name: 'Luxembourgish', code: 'lb' },
        { name: 'Javanese', code: 'jv' },
        { name: 'Malagasy', code: 'mg' },
        { name: 'Japanese', code: 'ja' },
        { name: 'Malay', code: 'ms' }
    ];

    static getNameByCode = (code) => {
        const languages = new SupportedLanguages();

        for (let i = 0; i < languages.languages.length; i++) {
            const lang = languages.languages[i];
    
            if (lang.code === code) {
                return lang.name;
            }
        }
    
        return null;
    }
}